name: Github Action doc generator
description: Github Action doc generator
author: jackton1
inputs:
  action:
    description: 'Path to the action.yml file'
    required: false
    default: action.yml
  col_max_width:
    description: 'Max width of a column'
    required: false
    default: '1000'
  col_max_words:
    description: 'Max number of words per line in a column'
    required: false
    default: '5'
  output:
    description: 'Path to the output file'
    required: false
    default: README.md
  input_columns:
    description: 'List of Input columns names to display, default (display all columns)'
    required: false
  output_columns:
    description: 'List of Output column names to display, default (display all columns)'
    required: false
  bin_path:
    description: 'Path to the binary'
    required: false

runs:
  using: 'composite'
  steps:
    - run: |
        # "Running auto-doc..."
        bash $GITHUB_ACTION_PATH/entrypoint.sh
      id: auto-doc
      shell: bash
      env:
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-specifying-inputs
        INPUT_ACTION: ${{ inputs.action }}
        INPUT_COL_MAX_WIDTH: ${{ inputs.col_max_width }}
        INPUT_COL_MAX_WORDS: ${{ inputs.col_max_words }}
        INPUT_OUTPUT: ${{ inputs.output }}
        INPUT_INPUT_COLUMNS: ${{ inputs.input_columns }}
        INPUT_OUTPUT_COLUMNS: ${{ inputs.output_columns }}
        INPUT_BIN_PATH: ${{ inputs.bin_path }}

branding:
  icon: file-text
  color: white
