name: Action auto doc generator
description: Action auto doc generator
author: jackton1
inputs:
  action:
    description: 'Path to the action.yml file'
    required: false
    default: action.yml
  col_max_width:
    description: 'Max width of a column'
    required: false
    default: '1000'
  col_max_words:
    description: 'Max number of words per line in a column'
    required: false
    default: '6'
  output:
    description: 'Path to the output file'
    required: false
    default: README.md

runs:
  using: 'composite'
  steps:
    - run: |
        curl -sf https://gobinaries.com/github.com/tj-actions/auto-doc@v1.2.2 | PREFIX=. sh
        ./auto-doc --action="${{ inputs.action }}" --output="${{ inputs.output }}" --colMaxWidth="${{ inputs.col_max_width }}" --colMaxWords="${{ inputs.col_max_words }}"
        rm -f ./auto-doc
      shell: bash
branding:
  icon: file-text
  color: white
