name: Action auto doc generator
description: Action auto doc generator
author: jackton1
inputs:
  action:
    description: 'Path to the action.yml file'
    required: true
    default: action.yml
  output:
    description: 'Output file'
    required: true
    default: README.md

runs:
  using: 'composite'
  steps:
    - run: |
        curl -sf https://gobinaries.com/github.com/tj-actions/auto-doc@v1.1.2 | PREFIX=. sh
        ./auto-doc --action="${{ inputs.action }}" --output="${{ inputs.output }}"
        rm -f ./auto-doc
      shell: bash
branding:
  icon: file-text
  color: white
