name: Lint
on:
  push:
    branches:
        - 'main'
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
      - 'Makefile'
      - '.github/workflows/lint.yml'
    branches:
      - 'main'

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

  golangci-lint:
    name: golangci lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version: "1.14.4"
